### ISSUE TITLE
Add license for storex-hub

### ISSUE THREAD

**Issue by brianredbeard** [WorldBrain/storex-hub#10]
I'm _assuming_ that storex-hub would have a similar license to [storex] (i.e. MIT) but having that ratified and:
  - added to `package.json`
  - present in a `LICENSE` file
  - flagged in repository settings

 would be _killer_.

**Comment by blackforestboi** [comment]
Hey @brianredbeard 
Thanks for the note, indeed MIT is the License to go. Will add asap.

**Comment by brianredbeard** [comment]
Resolved by 71d6967
